import Head from "next/head";
import Layout from "../components/layout";
import { SimpleGrid, Heading } from "@chakra-ui/react";
import ContentCard from "../components/contentCard/contentCard";
import SearchContext from "./SearchContext";
import { useContext, useState, useEffect } from "react";
import useAuth from "../hooks/useAuth";

const MOVIE_API_KEY = "fa940f6d4f0f73fb45419d96bae71b25";

export default function Bookmark() {
  const [BookMarkMovie, setBookMarkMovie] = useState([]);
  const { user } = useAuth();
  const { refreshData, bookmark } = useContext(SearchContext);

  useEffect(() => {
    refreshData();
  }, [user]);

  useEffect(() => {
    bookmark.map((item) => {
      fetch(
        `https://api.themoviedb.org/3/${item.mediaType}/${item.mediaId}?api_key=${MOVIE_API_KEY}&language=en-US`
      )
        .then((res) => res.json())
        .then((data) => {
          data["firebaseID"] = item.id;
          setBookMarkMovie((prevBookMarkMovie) => [...prevBookMarkMovie, data]);
        });
    });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading
          as="h2"
          variant="h2"
          marginBottom="16px"
          fontSize={{ md: "2rem" }}
        >
          Bookmarked Movies & Tv Shows
        </Heading>
        <SimpleGrid
          columns={{ sm: 2, md: 3, lg: 4 }}
          spacingX="15px"
          spacingY="16px"
          marginBottom="60px"
        >
          {BookMarkMovie &&
            BookMarkMovie.map((content, index) => {
              return (
                <ContentCard
                  firebaseID={content.firebaseID}
                  id={content.id}
                  title={content.title ? content.title : content.name}
                  release={
                    content.release_date
                      ? content.release_date
                      : content.first_air_date
                  }
                  mediaType="movie"
                  thumbnail={content.backdrop_path}
                  rating={content.vote_average}
                  key={index}
                />
              );
            })}
        </SimpleGrid>
      </Layout>
    </>
  );
}
