import Head from "next/head";
import Layout from "../components/layout";
import ContentCard from "../components/contentCard/contentCard";
import SearchContext from "./SearchContext";
import useAuth from "../hooks/useAuth";
import { SimpleGrid, Heading } from "@chakra-ui/react";
import { useContext, useState, useEffect } from "react";
import { useAutoAnimate } from "@formkit/auto-animate/react";

const MOVIE_API_KEY = "fa940f6d4f0f73fb45419d96bae71b25";

export default function Bookmark() {
  const { user } = useAuth();
  const [animationParent] = useAutoAnimate();
  const { refreshData, bookmark } = useContext(SearchContext);

  useEffect(() => {
    refreshData();
  }, [user]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading
          as="h2"
          variant="h2"
          marginBottom="16px"
          fontSize={{ md: "2rem" }}
        >
          {!user
            ? "Login to add Movies & Tv Shows to bookmarks"
            : "Bookmarked Movies & Tv Shows"}
        </Heading>
        <SimpleGrid
          columns={{ sm: 2, md: 3, lg: 4 }}
          spacingX="15px"
          spacingY="16px"
          marginBottom="60px"
          ref={animationParent}
        >
          {bookmark &&
            bookmark.map((content, index) => {
              return (
                <ContentCard
                  firebaseID={content.id}
                  id={content.mediaId}
                  title={content.title ? content.title : content.name}
                  release={
                    content.release_date
                      ? content.release_date
                      : content.first_air_date
                  }
                  mediaType={content.media_type}
                  thumbnail={content.backdrop_path}
                  rating={content.vote_average}
                  key={index}
                />
              );
            })}
        </SimpleGrid>
      </Layout>
    </>
  );
}
