import Head from "next/head";
import Layout from "../components/layout";
import {
  Input,
  FormControl,
  Box,
  SimpleGrid,
  Heading,
  Slide,
  Chakra,
} from "@chakra-ui/react";
import SearchBar from "../components/search/search";
import ContentCard from "../components/contentCard/contentCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SearchBar />
        <Heading
          as="h2"
          variant="h2"
          marginBottom="16px"
          fontSize={{ md: "2rem" }}
        >
          Movies
        </Heading>
        <SimpleGrid
          columns={{ sm: 2, md: 3, lg: 4 }}
          spacingX="15px"
          spacingY="16px"
          marginBottom="60px"
        >
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
          <ContentCard />
        </SimpleGrid>
      </Layout>
    </>
  );
}
