name: Code Check
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ ESLint, ʦ TypeScript, 💅 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup bun
        uses: oven-sh/setup-bun@v2

      - name: 🔬 Lint
        run: bun lint

      - name: 🔎 Type check
        run: bun typecheck

      - name: 💅 Prettier check
        run: bun format:check
